import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <article className="prose prose-sm max-w-none text-muted-foreground prose-headings:text-foreground prose-headings:font-semibold prose-a:text-primary prose-strong:text-foreground">
      <div className="mb-10">
        <p className="text-xs uppercase tracking-widest text-primary font-semibold mb-2">Legal</p>
        <h1 className="text-3xl font-bold tracking-tight text-foreground" style={{ fontFamily: "'Instrument Serif', serif" }}>
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">Effective date: September 1, 2026 · Last updated: September 1, 2026</p>
      </div>

      <Section title="1. Acceptance of Terms">
        <p>By accessing or using the FoundersDeck platform (&ldquo;Service&rdquo;), you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to all of these Terms, do not use the Service.</p>
        <p>These Terms constitute a legally binding agreement between you (&ldquo;User,&rdquo; &ldquo;you,&rdquo; or &ldquo;your&rdquo;) and FoundersDeck (&ldquo;FoundersDeck,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). FoundersDeck reserves the right to update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
      </Section>

      <Section title="2. Description of Service">
        <p>FoundersDeck is a software-as-a-service platform that provides tools for startup founders, including but not limited to: AI-assisted pitch deck generation, business plan builders, financial projection tools, investor relationship management, legal document templates, contingency planning tools, and data room organization tools.</p>
        <p><strong>Not professional advice.</strong> All content, templates, outputs, and materials generated by or through the Service are for informational and organizational purposes only. Nothing in the Service constitutes legal, financial, investment, accounting, or business advice. You should consult qualified professionals before making any legal, financial, or business decisions. FoundersDeck is not a law firm, financial advisor, or investment firm.</p>
        <p><strong>AI-generated content.</strong> The Service uses artificial intelligence to generate content. AI-generated content may be inaccurate, incomplete, or outdated. You are solely responsible for reviewing, verifying, and taking responsibility for any content you use, share, or distribute from the Service.</p>
      </Section>

      <Section title="3. Account Registration">
        <p>You must create an account to use certain features of the Service. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate and complete.</p>
        <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account at <a href="mailto:security@foundersdeck.co">security@foundersdeck.co</a>.</p>
        <p>You must be at least 18 years of age to create an account and use the Service.</p>
      </Section>

      <Section title="4. Subscriptions and Billing">
        <p><strong>Subscription plans.</strong> We offer Free, Pro, and Accelerator subscription plans. Features available under each plan are described on our Pricing page and may be updated from time to time.</p>
        <p><strong>Payment.</strong> By subscribing to a paid plan, you authorize us to charge your payment method on a recurring basis at the applicable subscription rate. All fees are in Canadian dollars (CAD) unless otherwise stated and are non-refundable except as expressly set forth herein.</p>
        <p><strong>Free trial.</strong> If you begin a free trial, your payment method will be charged at the end of the trial period unless you cancel before the trial ends.</p>
        <p><strong>Auto-renewal.</strong> Subscriptions automatically renew at the end of each billing period unless cancelled. You may cancel at any time through your account settings; cancellation takes effect at the end of the current billing period.</p>
        <p><strong>Refunds.</strong> We offer a pro-rated refund within 7 days of the initial purchase of a paid plan if you are dissatisfied with the Service. After 7 days, no refunds are provided. To request a refund, contact <a href="mailto:billing@foundersdeck.co">billing@foundersdeck.co</a>.</p>
        <p><strong>Price changes.</strong> We may change subscription fees upon 30 days&rsquo; notice. Your continued use of the Service after such notice constitutes acceptance of the new fees.</p>
      </Section>

      <Section title="5. Acceptable Use">
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Violate any applicable law or regulation, including securities laws, anti-fraud statutes, or data protection laws;</li>
          <li>Create or distribute materially false, misleading, or fraudulent content intended to deceive investors;</li>
          <li>Infringe the intellectual property rights of any third party;</li>
          <li>Upload or transmit malware, viruses, or other harmful code;</li>
          <li>Attempt to gain unauthorized access to other accounts or systems;</li>
          <li>Scrape, reverse-engineer, or extract data from the Service in bulk without our express written consent;</li>
          <li>Resell or sublicense access to the Service to third parties without our prior written approval;</li>
          <li>Use the Service to harass, threaten, or harm any person.</li>
        </ul>
        <p>We reserve the right to suspend or terminate your account immediately for violation of these provisions.</p>
      </Section>

      <Section title="6. Intellectual Property">
        <p><strong>Our IP.</strong> The Service, including all software, content, designs, trademarks, and trade names, is owned by FoundersDeck and its licensors and is protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works of our proprietary materials without our written consent.</p>
        <p><strong>Your content.</strong> You retain ownership of all content, data, and materials you create, upload, or generate using the Service (&ldquo;User Content&rdquo;). By using the Service, you grant FoundersDeck a limited, non-exclusive, royalty-free licence to process, store, and display your User Content solely to provide the Service to you.</p>
        <p><strong>AI outputs.</strong> We do not claim ownership of outputs generated by AI tools in the Service based on your inputs. You are responsible for ensuring that your use of AI-generated outputs does not infringe third-party intellectual property rights.</p>
        <p><strong>Feedback.</strong> Any feedback, suggestions, or ideas you submit regarding the Service may be used by FoundersDeck without obligation or compensation to you.</p>
      </Section>

      <Section title="7. Privacy">
        <p>Your use of the Service is also governed by our <a href="/legal/privacy">Privacy Policy</a>, which is incorporated into these Terms by reference. By using the Service, you consent to the collection and use of your information as described therein.</p>
      </Section>

      <Section title="8. Third-Party Services">
        <p>The Service integrates with or links to third-party services (e.g., payment processors, analytics providers, AI model providers). Your use of such services is governed by their respective terms and privacy policies. FoundersDeck is not responsible for the practices or content of any third-party services.</p>
      </Section>

      <Section title="9. Disclaimer of Warranties">
        <p><strong>THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.</strong> TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, FOUNDERSDECK DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, COMPLETENESS, RELIABILITY, SECURITY, AND AVAILABILITY.</p>
        <p>WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT ANY DEFECTS WILL BE CORRECTED. WE DO NOT WARRANT THAT AI-GENERATED CONTENT IS ACCURATE, COMPLETE, OR SUITABLE FOR ANY PURPOSE.</p>
        <p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM FOUNDERSDECK OR THROUGH THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.</p>
      </Section>

      <Section title="10. Limitation of Liability">
        <p><strong>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL FOUNDERSDECK, ITS DIRECTORS, EMPLOYEES, AGENTS, PARTNERS, OR LICENSORS BE LIABLE FOR ANY:</strong></p>
        <ul>
          <li>Indirect, incidental, special, consequential, or punitive damages;</li>
          <li>Loss of profits, revenue, data, goodwill, or business opportunities;</li>
          <li>Damages resulting from reliance on AI-generated content;</li>
          <li>Damages resulting from investment decisions made using the Service;</li>
          <li>Any other damages arising out of or relating to your use of the Service.</li>
        </ul>
        <p><strong>IN NO EVENT SHALL FOUNDERSDECK&rsquo;S TOTAL AGGREGATE LIABILITY TO YOU EXCEED THE GREATER OF: (A) THE TOTAL FEES PAID BY YOU TO FOUNDERSDECK IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE CLAIM, OR (B) ONE HUNDRED CANADIAN DOLLARS (CAD $100).</strong></p>
        <p>Some jurisdictions do not allow the exclusion or limitation of certain damages. In such jurisdictions, our liability shall be limited to the maximum extent permitted by law.</p>
      </Section>

      <Section title="11. Indemnification">
        <p>You agree to indemnify, defend, and hold harmless FoundersDeck, its officers, directors, employees, agents, and licensors from and against any claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or relating to: (a) your use of the Service; (b) your User Content; (c) your violation of these Terms; (d) your violation of any applicable law or the rights of any third party; or (e) any misrepresentations you make to investors or other parties using materials created through the Service.</p>
      </Section>

      <Section title="12. Termination">
        <p>We may suspend or terminate your access to the Service at any time, with or without notice, for any reason, including violation of these Terms. Upon termination, your right to use the Service immediately ceases. We may delete your User Content after account termination, subject to our data retention obligations under applicable law.</p>
        <p>You may terminate your account at any time by contacting <a href="mailto:support@foundersdeck.co">support@foundersdeck.co</a>. Termination does not entitle you to a refund of any prepaid fees, except as expressly provided in Section 4.</p>
      </Section>

      <Section title="13. Governing Law and Dispute Resolution">
        <p><strong>Governing law.</strong> These Terms and any disputes arising hereunder shall be governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict of law principles.</p>
        <p><strong>Informal resolution.</strong> Before filing any formal legal claim, you agree to attempt to resolve any dispute informally by contacting us at <a href="mailto:legal@foundersdeck.co">legal@foundersdeck.co</a>. We will attempt to resolve the dispute within 30 days.</p>
        <p><strong>Arbitration.</strong> If informal resolution fails, any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be resolved by binding arbitration administered in Toronto, Ontario, Canada, in accordance with the Arbitration Act, 1991 (Ontario), except that either party may seek injunctive relief in a court of competent jurisdiction for intellectual property infringement or other emergency relief.</p>
        <p><strong>Class action waiver.</strong> YOU AGREE TO RESOLVE DISPUTES WITH FOUNDERSDECK ON AN INDIVIDUAL BASIS AND WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>
        <p><strong>Jurisdiction.</strong> If arbitration is not enforceable, you consent to the exclusive jurisdiction of the courts of Toronto, Ontario, Canada.</p>
      </Section>

      <Section title="14. Modifications">
        <p>We reserve the right to modify these Terms at any time. Material changes will be notified via email or a prominent notice on the Service at least 14 days before taking effect. Your continued use of the Service after the effective date of any changes constitutes your acceptance of the revised Terms.</p>
      </Section>

      <Section title="15. Miscellaneous">
        <p><strong>Entire agreement.</strong> These Terms, together with the Privacy Policy and any other policies incorporated herein, constitute the entire agreement between you and FoundersDeck regarding the Service.</p>
        <p><strong>Severability.</strong> If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.</p>
        <p><strong>Waiver.</strong> Our failure to enforce any provision of these Terms shall not constitute a waiver of our right to enforce such provision in the future.</p>
        <p><strong>Assignment.</strong> You may not assign or transfer your rights under these Terms without our prior written consent. We may assign our rights and obligations without restriction.</p>
        <p><strong>Contact.</strong> For questions about these Terms, contact us at <a href="mailto:legal@foundersdeck.co">legal@foundersdeck.co</a>.</p>
      </Section>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="mb-3 text-base font-semibold text-foreground">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed">{children}</div>
    </section>
  );
}
